version: '3'
services:
        web:
                image: sheriff
                build: .

                ports:
                        - "8325:8325"
                volumes:
                        - ./instance:/app/instance
                restart: unless-stopped
                