version: '3'
services:
        web:
                image: flask_open
                build: .
                
                ports:
                        - "8307:8307"
                volumes:
                        - ./instance:/app/instance
                restart: unless-stopped

        socketio:
                image: socket_open
                build: ./socket
                ports:
                        - "8500:8500"
    
                restart: unless-stopped